apiVersion: v1
kind: Service
metadata:
  name: chaitanya-march-11
spec:
  selector:
    app: chaitanya-march-11
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: chaitanya-march-11-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: chaitanya-march-11.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: chaitanya-march-11
#             port:
#               number: 80
